services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: tomboy
      POSTGRES_PASSWORD: tom@1234567
      POSTGRES_DB: school
    ports:
      - '5432:5432'
    networks:
      - app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .  
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://tomboy:tom@1234567@postgres_db:5432/school
    depends_on:
      - postgres
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres_data:
